
write_typing("write_code", process = process)
write_typing("use_r", process = process)
write_typing("write_functions", process = process)
write_typing("load_all", process = process)
write_typing("write_library", process = process)
write_typing("use_package", process = process)
write_typing("use_package_code", process = process)
write_typing("use_package_install", process = process)
write_typing("test_prep", typing_speed = .00001, process = process)
write_typing("fiddle", process = process)
write_typing("use_test", process = process)
write_typing("comment", process = process)
write_typing("use_roxygen_rmd", process = process)
write_typing("roxygen", typing_speed = .00001, process = process)
write_typing("document", process = process)
write_typing("use_data_raw", process = process)
write_typing("use_data", process = process)
write_typing("use_vignette", process = process)
write_typing("use_inst", process = process)
write_typing("use_toplevel", process = process)
write_typing("install", process = process)
